language: php
php:
  - "5.3"
  - "5.4"

before_install:
  - sudo apt-get install gearman-server gearman-tools
  - gearmand &
  - sudo apt-get install libgearman-dev
  - /bin/bash ./installer.sh
  - phpenv rehash
  - php server.php &

script:
  - cd tests/
  - phpunit
