language: php
php:
  - "5.3"
  - "5.4"

before_install:
  - sudo apt-get install gearman-job-server libgearman-dev gearman
  - sudo /etc/init.d/gearman-job-server status
  - echo 'foo' | /bin/nc -q 2 127.0.0.1 4730
  - /bin/bash ./installer.sh
  - phpenv rehash
  - php server.php &

script:
  - cd tests/
  - phpunit
