language: php
php:
  - "5.3"
  - "5.4"

before_install:
  - sudo apt-get install gearman-job-server libgearman-dev gearman
  - gearmand -d
  - /bin/bash ./installer.sh
  - phpenv rehash
  - php server.php &

script:
  - cd tests/
  - phpunit
